### ISSUE TITLE
Can I contribute in this project. Have you any issue in this?

### ISSUE THREAD

**Issue by aryan2621** [amandewatnitrr/Octafest#15]

**Comment by amandewatnitrr** [comment]
Yes sure. No problem, you can make a code-of-conduct page for us if you wish to do so.

**Comment by amandewatnitrr** [comment]
or you can help us making a better version of our workshop page. The Workshop page is on another repo named "octafest-workshop", you can find it among my repositories.

**Comment by aryan2621** [comment]
> Yes sure. No problem, you can make a code-of-conduct page for us if you wish to do so.

Sure I will do the work .What is your expectations from the page. Have you any particular example

**Comment by aryan2621** [comment]
> or you can help us making a better version of our workshop page. The Workshop page is on another repo named "octafest-workshop", you can find it among my repositories.

Till then I am working on this

**Comment by amandewatnitrr** [comment]
> > Yes sure. No problem, you can make a code-of-conduct page for us if you wish to do so.
> 
> Sure I will do the work .What is your expectations from the page. Have you any particular example

Will look into this soon and send you samples soon, till than please keep a check on this issue continuously.
