### ISSUE TITLE
Fix outline buttons hover effect

### ISSUE THREAD

**Issue by polgarj** [amandewatnitrr/Octafest#3]
Instead of this:
<img width="326" alt="kép" src="https://user-images.githubusercontent.com/32764219/135605512-05fc3061-8e1d-47df-b6b9-e310911e5cca.png">

I would go with this:
<img width="402" alt="kép" src="https://user-images.githubusercontent.com/32764219/135605466-784fdf49-3f04-435a-b339-c383434f55cf.png">

And instead of this:
<img width="271" alt="kép" src="https://user-images.githubusercontent.com/32764219/135605572-7bb53078-6981-41ac-9653-313dbce1a4c5.png">

This would work better:
<img width="275" alt="kép" src="https://user-images.githubusercontent.com/32764219/135605808-b1c494f7-66f1-4c54-9287-93736a9753b3.png">

**Comment by amandewatnitrr** [comment]
Issue Resolved
