### ISSUE TITLE
Copied Website

### ISSUE THREAD

**Issue by ankitrajbiswal** [amandewatnitrr/Octafest#5]
The website lacks originality, even the coders have copied the entire code from the website of Hackclub ITER.
This is not promoted in the coding community.

**Comment by amandewatnitrr** [comment]
Hello Sir, 
We do accept the fact that we copied some traces but we didn't use the orignal thing as it is and have made some changes. It was just a miss-preparation on our side and we apologise for that. We accept it and for this we will be giving you credits on readme for that. i hope that resolves the issue.
