### ISSUE TITLE
[ISSUE] No originality

### ISSUE THREAD

**Issue by Saswat7101** [amandewatnitrr/Octafest#6]
This website has been completely copied from [https://iter.hackclub.com/](https://iter.hackclub.com/). Only some color changes and nothing original

**Comment by amandewatnitrr** [comment]
Hello Sir,
We do accept the fact that we copied some traces but we didn't use the orignal thing as it is and have made some changes. It was just a miss-preparation on our side and we apologise for that. We accept it and for this we will be giving you credits on readme for that. i hope that resolves the issue. We do expect a soft response from your side though as we accept our mistake and will be giving on credits in rademe.
