### ISSUE TITLE
Plagiarised Content

### ISSUE THREAD

**Issue by SS-2213** [amandewatnitrr/Octafest#7]
The whole content of the website is just a copy of the website of the official website of HACK CLUB ITER.

**Comment by amandewatnitrr** [comment]
Hello Mam,
We do accept the fact that we copied some traces but we didn't use the orignal thing as it is and have made some changes. It was just a miss-preparation on our side and we apologise for that. We accept it and for this we will be giving you credits on readme for that. i hope that resolves the issue. We expect a kind response from your side further as we accept it and will be adding the credits quick soon.
