### ISSUE TITLE
Footer UI can be improved.

### ISSUE THREAD

**Issue by sahilsaini1107** [amandewatnitrr/Octafest#9]

**Comment by sahilsaini1107** [comment]
I would like to do it. May I??

**Comment by amandewatnitrr** [comment]
Do suggest some changes and feel free to contribute.

**Comment by amandewatnitrr** [comment]
> I would like to do it. May I??

Sure, go ahead. but do share an screenshot of the localhost while making a PR.

**Comment by sahilsaini1107** [comment]
in large screen size, content is not well placed, also discord icon and discord need to be in same line acc. to me.

**Comment by amandewatnitrr** [comment]
> in large screen size, content is not well placed, also discord icon and discord need to be in same line acc. to me.

feel free to have a look on them and make a PR.

**Comment by sahilsaini1107** [comment]
Also will this count in hacktoberfest??

**Comment by amandewatnitrr** [comment]
yup
